name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./DeckOfCardsAPITest/DeckOfCards/
    - name: Build
      run: dotnet build --no-restore ./DeckOfCardsAPITest/DeckOfCards/
    - name: Test
      run: dotnet test ./DeckOfCardsAPITest/DeckOfCards/ --no-build --verbosity detailed -s:RunSettings\prd.runsettings
